### ISSUE TITLE
请问如何修改Chapter编号与标题之间的空格

### ISSUE THREAD

**Issue by NyankoSong** [skymagician/cugbthesis#1]
模板中的Chapter编号与标题的水平距离较本科Word文档中稍宽，但是始终未能找到减少这一空格的办法（只能搜索到Section的配置方法），因此冒昧在这里请教，希望能得到解决，谢谢。
当前：
# 1 &emsp; 引言
我希望得到的：
# 1 &ensp; 引言

**Comment by skymagician** [comment]
这个我暂时还没找到解决办法。本科的模板与硕博的差异较大，这个模板可能不适合本科生使用。

**Comment by NyankoSong** [comment]
> 这个我暂时还没找到解决办法。本科的模板与硕博的差异较大，这个模板可能不适合本科生使用。

好吧，我后期直接编辑PDF算了，还是感谢回复！

**Comment by NyankoSong** [comment]
> 这个我暂时还没找到解决办法。本科的模板与硕博的差异较大，这个模板可能不适合本科生使用。

你好，我在其他地方找到了解决方案，放在这里供参考。
需要在
`\ctexset{chapter={...}}`
中添加
`aftername=\quad, % 或者\qquad等`
就可以设置这一空格的长短了。
来源：[https://ask.latexstudio.net/ask/question/7390.html](url)
